/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zenspace.pkgfinal;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Arpita mallik
 */
public class Reciept extends javax.swing.JFrame {

    /**
     * Creates new form Reciept
     */
    String username = null;
    DefaultTableModel model;
    public Reciept() {
        initComponents();
    }
    public Reciept(String user, Vector<String> Product,Vector<String> Type,Vector<Integer> Price,Vector<Integer> Quantity,String methodOfPay,Integer Amount,String Name){
        initComponents();
        username = user;
        DefaultTableModel model=(DefaultTableModel)receipttab.getModel();
        TableColumn column1 = receipttab.getColumnModel().getColumn(0);
        TableColumn column2 = receipttab.getColumnModel().getColumn(1);
        TableColumn column3 = receipttab.getColumnModel().getColumn(2);
        TableColumn column4 = receipttab.getColumnModel().getColumn(3);
        TableColumn column5 = receipttab.getColumnModel().getColumn(4);
        column1.setPreferredWidth(100);
        column2.setPreferredWidth(30);
        column3.setPreferredWidth(10);
        column4.setPreferredWidth(30);
        column5.setPreferredWidth(30);
        for(int i=0;i<Product.size();i++){
            Integer TotalPrice = Quantity.get(i)*Price.get(i);
            model.addRow(new Object[]{Product.get(i), Type.get(i), Price.get(i), Quantity.get(i), TotalPrice});
        }
        jLabel11.setText(Amount.toString());
        jLabel9.setText(methodOfPay);
        jLabel12.setText(Name);
         LocalDateTime currentDateTime = LocalDateTime.now();

        // Define a format for the date and time
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

        // Format the current date and time using the defined format
        String formattedDateTime = currentDateTime.format(formatter);
        jLabel14.setText(formattedDateTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelToPrint = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipttab = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelToPrint.setBackground(new java.awt.Color(255, 239, 224));
        panelToPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setToolTipText("");
        jLabel14.setOpaque(true);
        panelToPrint.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ZenSpace Logo sm2.png"))); // NOI18N
        panelToPrint.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -10, 240, 109));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("---------------------------------------------------------------------------------");
        panelToPrint.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 440, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("THANK YOU!");
        panelToPrint.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 160, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("---------------------------------------------------------------------------------");
        panelToPrint.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 440, -1));

        receipttab.setFont(new java.awt.Font("Century", 1, 8)); // NOI18N
        receipttab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT NAME", "TYPE", "PRICE", "QUANTITY", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        receipttab.setGridColor(new java.awt.Color(255, 255, 255));
        receipttab.setSelectionBackground(new java.awt.Color(255, 255, 255));
        receipttab.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(receipttab);

        panelToPrint.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 430, 180));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Method of paying:");
        panelToPrint.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 170, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Total");
        panelToPrint.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panelToPrint.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 460, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setText("****RECEIPT***");
        panelToPrint.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 230, 80));

        jLabel8.setBackground(new java.awt.Color(255, 204, 153));
        jLabel8.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        jLabel8.setText("Customer Name:");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        panelToPrint.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel9.setOpaque(true);
        panelToPrint.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 210, 30));

        jLabel10.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel10.setText("BDT");
        panelToPrint.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel11.setOpaque(true);
        panelToPrint.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 110, 30));
        panelToPrint.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 310, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-30.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        panelToPrint.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 30, 30));

        jLabel15.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel15.setText("Order Date & Time:");
        panelToPrint.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 145, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 238, 221));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jButton1.setText("Print Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelToPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelToPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(474, 686));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        printRecord(panelToPrint);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        new UserHomepage(username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    public void getsum()
    {
       

        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reciept().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelToPrint;
    private javax.swing.JTable receipttab;
    // End of variables declaration//GEN-END:variables
    
    private void printRecord(JPanel panel){
        PrinterJob printerJob  = PrinterJob.getPrinterJob();
        
        printerJob.setJobName("Print Record");
        
        printerJob.setPrintable(new Printable(){
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException{
                if(pageIndex > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D graphics2D = (Graphics2D)graphics;
                graphics2D.translate(pageFormat.getImageableX()*2, pageFormat.getImageableY()*2);
                graphics2D.scale(0.5,0.5);
                panel.paint(graphics2D);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean returningResult = printerJob.printDialog();
        if(returningResult){
            try{
                printerJob.print();
            }catch(PrinterException printerException){
                JOptionPane.showMessageDialog(this,"Print error:"+ printerException.getMessage());
            }
        }
    }
}


