/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zenspace.pkgfinal;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;

/**
 *
 * @author Arpita mallik
 */
public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */
    String filename = null;
    byte[] imgd;
    static int milisecs = 0;
    static int secs = 0;
    static int mins = 0;
    static int hours = 0;
    static boolean state = false;
    private long selectedDurationMillis = 0;
    private long startTimeMillis = 0;
   
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String user=null;
    public UserProfile(){
        initComponents();
    }
    
    public UserProfile(String username) {
        user=username;
        initComponents();
        Connect();
        jLabel2.setText(username);
        try {
            pst=con.prepareStatement("select * from userinformation where USERNAME=?");
            pst.setString(1, user);
            rs=pst.executeQuery();
            while(rs.next()){
                String name=rs.getString("Username");
                String Fullname = rs.getString("Name");
                jTextField1.setText(name);
                byte[] dp;
                dp = rs.getBytes("ProfilePicture");
                ImageIcon propic = null;
                Image image=null;
                if(dp!=null){
                    propic = new ImageIcon(dp);
                    image = propic.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
                }
                jLabel4.setIcon(new ImageIcon(image));
                jLabel3.setText(Fullname);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        Calendar calendar = Calendar.getInstance();
        calendar.set(2001, Calendar.OCTOBER, 16); // Set to January 1, 2023 as an example
        Date defaultDate = calendar.getTime();
        try {
            pst = con.prepareStatement("Select * from userinformation where username = ?");
            pst.setString(1, user);
            rs = pst.executeQuery();
            while(rs.next()){
                Date dt = rs.getDate("DATE_OF_BIRTH");
                jDateChooser1.setDate(dt);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pst = con.prepareStatement("Select * from userprofileinfo where Username=?");
            pst.setString(1, user);
            rs = pst.executeQuery();
            while(rs.next()){
                   int Score = rs.getInt("MindfulnessScore");
                   int Crs = rs.getInt("CoursesPurchased");
                   int alb = rs.getInt("AlbumsPurchased");
                   int book = rs.getInt("BooksPurchased");
                   int march = rs.getInt("MerchandisePurchased");
                   int don = rs.getInt("DonationMade");
                   
                   jLabel22.setText(Integer.toString(Crs));
                   jLabel23.setText(Integer.toString(alb));
                   jLabel24.setText(Integer.toString(book));
                   jLabel25.setText(Integer.toString(march));
                   jLabel15.setText(Integer.toString(don));
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pst = con.prepareStatement("select * from mindfulnessscore where USERNAME = ?");
            pst.setString(1, user);
            rs = pst.executeQuery();
            while(rs.next()){
                int Score = rs.getInt("Score");
                jLabel21.setText(Integer.toString(Score));
            }
            //String sc = score.toString();
            
        } catch (SQLException ex) {
            Logger.getLogger(QuizPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost/zenspace","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(homepage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profiletab = new javax.swing.JTabbedPane();
        Overview = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Settings = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel30 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel31 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        timer = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        min = new javax.swing.JLabel();
        sec = new javax.swing.JLabel();
        milisec = new javax.swing.JLabel();
        hour = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        pause = new javax.swing.JButton();
        restart = new javax.swing.JButton();
        start = new javax.swing.JButton();
        durationComboBox = new javax.swing.JComboBox<>();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 243, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profiletab.setPreferredSize(new java.awt.Dimension(1180, 450));

        Overview.setBackground(new java.awt.Color(255, 226, 198));
        Overview.setPreferredSize(new java.awt.Dimension(833, 420));
        Overview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Overview.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 250, 310));

        jLabel5.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel5.setText("Longest Streak:");
        Overview.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 150, 55));

        jLabel49.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel49.setText("Back to home");
        jLabel49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });
        Overview.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 100, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-mindfulness-78.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        Overview.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 82, -1));

        jLabel3.setBackground(new java.awt.Color(255, 223, 191));
        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setText("Ratnajit Dhar");
        Overview.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 250, 50));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setText("(ratnajit_dhar)");
        Overview.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel7.setText("Total Minutes:");
        Overview.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 140, 55));

        jLabel8.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel8.setText("Total Session:");
        Overview.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 130, 55));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/timer.png"))); // NOI18N
        Overview.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, 80));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medi.png"))); // NOI18N
        Overview.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, 70));

        jLabel11.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel11.setText("34");
        Overview.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 30, 40));

        jLabel12.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel12.setText("12");
        Overview.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, 50));

        jLabel13.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel13.setText("356");
        Overview.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, -1, 40));

        jLabel14.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel14.setText("Mindfulness Score:");
        Overview.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel15.setText("25.00");
        Overview.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, -1, 50));

        jLabel16.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel16.setText("Courses Purchased:");
        Overview.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel17.setText("Albums Purchased:");
        Overview.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel18.setText("Books Purchased:");
        Overview.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel19.setText("Merchandise Purchased:");
        Overview.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, -1, -1));

        jLabel20.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel20.setText("Donation Made:");
        Overview.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel21.setText("56");
        Overview.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, 50));

        jLabel22.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel22.setText("2");
        Overview.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, 50));

        jLabel23.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel23.setText("3");
        Overview.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, 50));

        jLabel24.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel24.setText("1");
        Overview.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 50, 50));

        jLabel25.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel25.setText("3");
        Overview.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, -1, 50));

        jLabel26.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel26.setText("Days");
        Overview.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel37.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeeeicon.png"))); // NOI18N
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        Overview.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 60, 60));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userbg big.png"))); // NOI18N
        Overview.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -80, 1720, 950));

        profiletab.addTab("Overview", Overview);

        Settings.setBackground(new java.awt.Color(255, 226, 198));
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
        });
        Settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Century", 1, 21)); // NOI18N
        jLabel27.setText("Username:");
        Settings.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 130, 30));

        jLabel50.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeeeicon.png"))); // NOI18N
        jLabel50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        Settings.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 60, 60));

        jTextField1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jTextField1.setText("ratnajit_dhar");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Settings.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 220, 34));

        jLabel51.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel51.setText("Back to home");
        jLabel51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });
        Settings.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 100, 40));

        jLabel48.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editicon.png"))); // NOI18N
        jLabel48.setText("Edit Profile");
        Settings.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 220, 50));

        jLabel28.setFont(new java.awt.Font("Century", 1, 21)); // NOI18N
        jLabel28.setText("Change Profile Picture:");
        Settings.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 250, -1));

        jButton1.setBackground(new java.awt.Color(179, 131, 83));
        jButton1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Upload New Profile Picture");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Settings.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 280, -1));

        jLabel29.setFont(new java.awt.Font("Century", 1, 21)); // NOI18N
        jLabel29.setText("Change Password:");
        Settings.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        Settings.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 220, -1));

        jLabel30.setFont(new java.awt.Font("Century", 1, 21)); // NOI18N
        jLabel30.setText("Confirm Password:");
        Settings.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jPasswordField2.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        Settings.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 220, -1));

        jLabel31.setFont(new java.awt.Font("Century", 1, 21)); // NOI18N
        jLabel31.setText("Contact No:");
        Settings.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jTextField2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Settings.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 220, -1));

        jDateChooser1.setBackground(new java.awt.Color(221, 154, 87));
        jDateChooser1.setToolTipText("");
        jDateChooser1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        Settings.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 220, -1));

        jLabel32.setFont(new java.awt.Font("Century", 1, 21)); // NOI18N
        jLabel32.setText("Date Of Birth:");
        Settings.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jCheckBox1.setText("Receive notifications from ZenSpace via Email");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Settings.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jButton2.setBackground(new java.awt.Color(179, 131, 83));
        jButton2.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Change");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Settings.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, -1, -1));

        jLabel38.setFont(new java.awt.Font("Century", 1, 21)); // NOI18N
        jLabel38.setText("Add Shipping Address:");
        Settings.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        jTextField3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Settings.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 220, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userbg big.png"))); // NOI18N
        Settings.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -30, 1460, 850));

        jLabel45.setFont(new java.awt.Font("Century", 1, 21)); // NOI18N
        jLabel45.setText("Username:");
        Settings.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 130, 30));

        jLabel46.setFont(new java.awt.Font("Century", 1, 21)); // NOI18N
        jLabel46.setText("Username:");
        Settings.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 130, 30));

        jLabel47.setFont(new java.awt.Font("Century", 1, 21)); // NOI18N
        jLabel47.setText("Change Password:");
        Settings.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        profiletab.addTab("Settings", Settings);

        timer.setBackground(new java.awt.Color(255, 226, 198));
        timer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/timergirl.png"))); // NOI18N
        timer.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 400, 370));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/timer guye.png"))); // NOI18N
        timer.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 510, 330));

        jButton6.setBackground(new java.awt.Color(183, 121, 58));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Set");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        timer.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, -1, 50));

        min.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        min.setText("00");
        timer.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 50, 60));

        sec.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        sec.setText("00");
        timer.add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 50, 60));

        milisec.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        milisec.setText("000");
        timer.add(milisec, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 80, 60));

        hour.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        hour.setText("00");
        timer.add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 50, 60));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel39.setText(":");
        timer.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, 60));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel40.setText(":");
        timer.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, 60));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel41.setText(":");
        timer.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, 60));

        pause.setBackground(new java.awt.Color(183, 121, 58));
        pause.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        pause.setForeground(new java.awt.Color(255, 255, 255));
        pause.setText("Pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        timer.add(pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, 130, 60));

        restart.setBackground(new java.awt.Color(183, 121, 58));
        restart.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        restart.setForeground(new java.awt.Color(255, 255, 255));
        restart.setText("Restart");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });
        timer.add(restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 680, 130, 60));

        start.setBackground(new java.awt.Color(183, 121, 58));
        start.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        timer.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 680, 130, 60));

        durationComboBox.setBackground(new java.awt.Color(221, 164, 106));
        durationComboBox.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        durationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 minutes", "10 minutes", "15 minutes", "25 minutes", "30 minutes" }));
        durationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationComboBoxActionPerformed(evt);
            }
        });
        timer.add(durationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 220, 50));

        jLabel52.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeeeicon.png"))); // NOI18N
        jLabel52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });
        timer.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 60, 60));

        jLabel54.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel54.setText("Back to home");
        jLabel54.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        timer.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 100, 40));

        jLabel35.setFont(new java.awt.Font("Century", 0, 36)); // NOI18N
        jLabel35.setText("Pomodoro Timer");
        timer.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 350, 50));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userbg big.png"))); // NOI18N
        timer.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, -20, 1460, 840));

        profiletab.addTab("timer", timer);

        jPanel1.add(profiletab, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -30, 1140, 850));

        jButton4.setBackground(new java.awt.Color(203, 137, 72));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("User Settings");
        jButton4.setBorderPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 210, 50));

        jButton5.setBackground(new java.awt.Color(203, 137, 72));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Pomodoro Session");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 210, 50));

        jButton3.setBackground(new java.awt.Color(203, 137, 72));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Overview");
        jButton3.setBorderPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ZenSpace Logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 10, 460, 120));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userbg big.png"))); // NOI18N
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 320, 860));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 920));

        jMenuBar1.setBackground(new java.awt.Color(255, 243, 232));
        jMenuBar1.setBorder(null);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jMenuBar1.setOpaque(true);

        jMenu1.setText("Overview");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("User Settings");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pomodoro Session");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon image = new ImageIcon(filename);
        try {
            FileInputStream fis = new FileInputStream(f);
            byte [] imageData = new byte[(int)f.length()];
            try {
                fis.read(imageData);
                fis.close();
            } catch (IOException ex) {
                Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            imgd=imageData;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon propic = null;
        Image image2=null;
        if(imgd!=null){
            propic = new ImageIcon(imgd);
            image2 = propic.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
            }
        jLabel4.setIcon(new ImageIcon(image2));
        try {
            pst=con.prepareStatement("Update userinformation Set ProfilePicture = ? where username = ?");
            pst.setBytes(1, imgd);
            pst.setString(2, user);
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        profiletab.setSelectedIndex(2);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
         state = true;
         
Thread t = new Thread() {
    public void run() {
        while (state) {
            try {
                sleep(1);
                milisecs++;
                if (milisecs > 999) {
                    milisecs = 0;
                    secs++;
                }
                if (secs > 59) {
                    secs = 0;
                    mins++;
                }
                if (mins > 59) {
                    mins = 0;
                    hours++;
                }
                
                // Update your Swing components using SwingUtilities.invokeLater
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        // Update your JLabels here
                        milisec.setText(String.valueOf(milisecs));
                        sec.setText(String.valueOf(secs));
                        min.setText(String.valueOf(mins));
                        hour.setText(String.valueOf(hours));

                    }
                    
                });
             
            } catch (InterruptedException e) {
                // Handle the exception here
            }
        }
    }
};
t.start();


    }//GEN-LAST:event_startActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        // TODO add your handling code here:
        state = false;
    }//GEN-LAST:event_pauseActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        // TODO add your handling code here:
        state = false;
        
        hours=0;
        mins=0;
        secs=0;
        milisecs=0;
       
        
        hour.setText("00 : ");
        min.setText("00 : ");
        sec.setText("00 : ");
        milisec.setText("00 ");
        
      
    }//GEN-LAST:event_restartActionPerformed

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        profiletab.setSelectedIndex(1);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        profiletab.setSelectedIndex(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        profiletab.setSelectedIndex(2);
    }//GEN-LAST:event_jMenu3MouseClicked
    
    
    
    
    
    
    private void durationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_durationComboBoxActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel2.setText("("+jTextField1.getText()+")");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // TODO add your handling code here:
        new UserHomepage(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        // TODO add your handling code here:
        new UserHomepage(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel49MouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
        // TODO add your handling code here:
        new UserHomepage(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel50MouseClicked

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
        // TODO add your handling code here:
        new UserHomepage(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                 state = true;
         
         String Duration = (String) durationComboBox.getSelectedItem();
         Integer Dur=0;
         if(Duration == "1 minutes") Dur=1;
         if(Duration == "10 minutes") Dur=10;
         if(Duration == "15 minutes") Dur=15;
         if(Duration == "20 minutes") Dur=20;
         if(Duration == "30 minutes") Dur=30;
         
         secs=0;
         mins=Dur;
Thread t = new Thread() {
    public void run() {
        while (state) {
            try {
                sleep(1);
                milisecs++;
                if (milisecs > 999) {
                    milisecs = 0;
                    secs--;
                }
                if (secs < 0) {
                    secs = 59;
                    mins--;
                }
                if (mins == 0) {
                    state=false;
                }
                
                // Update your Swing components using SwingUtilities.invokeLater
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        // Update your JLabels here
                        milisec.setText(String.valueOf(milisecs));
                        sec.setText(String.valueOf(secs));
                        min.setText(String.valueOf(mins));
                        hour.setText(String.valueOf(hours));

                    }
                    
                });
             
            } catch (InterruptedException e) {
                // Handle the exception here
            }
        }
    }
};
t.start();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        profiletab.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        profiletab.setSelectedIndex(1);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        profiletab.setSelectedIndex(2);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
        // TODO add your handling code here:
        new UserHomepage(user).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
        // TODO add your handling code here:
        new UserHomepage(user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel54MouseClicked

            /**
             * @param args the command line arguments
             */
            public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new UserProfile("ratnajit_dhar").setVisible(true);
                    }
                });
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Overview;
    private javax.swing.JPanel Settings;
    private javax.swing.JComboBox<String> durationComboBox;
    private javax.swing.JLabel hour;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel milisec;
    private javax.swing.JLabel min;
    private javax.swing.JButton pause;
    private javax.swing.JTabbedPane profiletab;
    private javax.swing.JButton restart;
    private javax.swing.JLabel sec;
    private javax.swing.JButton start;
    private javax.swing.JPanel timer;
    // End of variables declaration//GEN-END:variables

    
}
